Refactoring of drawGraph, and added graphUtils.c & .h.
Head9x/P1-projekt pull request #35
Opened 2023-12-05 13:17 UTC by chrnigi

### General Changes
Changed all instances of the typedef'd `tm` to `struct tm` in all in drawGraph.c, drawGraph.h, graphUtils.c and graphUtils.h (I might have missed some.) We should maybe change this for the rest of the source code aswell.

### Changes to `graph_exec`
`graph_exec` now takes the individual fields of the GraphParams struct as parameters, so as to more easily add possible parameters to this.

### New files: graphUtils.c and graphUtils.h
The new functions defined and declared in these are:

`time_input`:
 Returns a struct tm from user input.

`wcstrftime`: 
Takes 4 parameters,  `wchar_t * dest, size_t max_len, const char *format, const struct tm *timeptr`.  The function writes a `strftime` style format-string to a wchar_t array of size `max_len`.

`default_scatter_settings`: 
Calls the pbPlots function `GetDefaultScatterPlotSettings`, and adjusts the returned `ScatterPlotSetting` pointer to values fitting the project. The function takes a pointer to an already existing `ScatterPlotSeries` struct. Returns a pointer to the `ScatterPlotSettings` struct, which can be used as parameter to `DrawScatterPlotFromSettings`.

`free_scatter_settings`:
Takes a pointer to a `ScatterPlotSettings` struct, and frees all allocations in this struct, and also the struct itself.

`fill_data`:
Takes an `enum DataType`, a double pointer to an array, the size of the array, a `Datapoint` pointer to the CSV data, and a `struct tm`, which holds the users chosen day. The function fills the array with the data corresponding to the `DataType` parameter from the users chosen day onwards, untill the entire array has been filled.

### Changes in drawGraph.c
Changed functions to use the functions provided in graphUtils.h.

**New function `graph_comparison_scatter_exec`:**
Draws two scatterplots side by side :( . Takes an extra parameter compared to  `graph_scatterplot_exec` - a second type to graph. This second datatype is currently input in the switch-case in graph_exec, should maybe be changed if time allows.

Made wchar_t string arrays `type_strings` and `type_units` global static so all functions in drawGraph.c can access them.

2023-12-05 22:21 UTC, theis999 requested changes
Looks mostly fine. However without a good reason i'd prefer you kept using GetCSVData

2023-12-05 22:21 UTC, theis999 commented on PowerHouse/MenuFunctions.c
> +
Nice little whitespace

2023-12-05 22:21 UTC, theis999 commented on PowerHouse/MenuFunctions.c
> +    Datapoint* data = readCSV("datafiler/DK-DK2_2022_hourly.csv", &total_rows, true);
Why revert?

2023-12-05 22:21 UTC, theis999 commented on PowerHouse/MenuFunctions.c
> +    free(data);
Linked to above comment

2023-12-05 22:21 UTC, theis999 commented on PowerHouse/drawGraph.c
> +    ScatterPlotSeries **s1 = malloc(sizeof(ScatterPlotSeries));
I might have missed it, but i dont see where this is free'd

2023-12-05 22:21 UTC, theis999 commented on PowerHouse/drawGraph.c
> +    ScatterPlotSeries **s2 = malloc(sizeof(ScatterPlotSeries));
I might have missed it, but i dont see where this is free'd

2023-12-05 22:21 UTC, theis999 commented on PowerHouse/graphUtils.c
> +    size_t ret = mbstowcs(dest, temp, max_len);
Freaking c naming convention...

2023-12-05 22:56 UTC, chrnigi commented on PowerHouse/drawGraph.c
> +    ScatterPlotSeries **s2 = malloc(sizeof(ScatterPlotSeries));
Freed with `free_scatter_settings` just before function return.

2023-12-05 22:57 UTC, chrnigi commented on PowerHouse/drawGraph.c
> +    ScatterPlotSeries **s1 = malloc(sizeof(ScatterPlotSeries));
Freed with `free_scatter_settings` just before function return.

2023-12-05 22:58 UTC, chrnigi commented on PowerHouse/MenuFunctions.c
> +    Datapoint* data = readCSV("datafiler/DK-DK2_2022_hourly.csv", &total_rows, true);
Not on purpose, happened during merge. Will un-revert.

2023-12-06 06:41 UTC, theis999 commented on PowerHouse/drawGraph.c
> +    ScatterPlotSeries **s1 = malloc(sizeof(ScatterPlotSeries));
Fair enough

2023-12-06 06:42 UTC, theis999 approved these changes

2023-12-06 08:27 UTC, merged